name: Flutter Build and Deploy

on:
  push:
    branches:
      - master  

jobs:
  Generate-env-json:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        continue-on-error: false
        if: success()

      # Step 5: Create env.json file using baseurl from secrets
      - name: Generate Enviroment variable
        run: |
          mkdir -p assets
          cat << EOF > assets/env.json 
          ${{ secrets.ENV_JSON}}
          EOF
        shell: bash
        continue-on-error: false
        if: success()
      
      - name: Validate env.json
        run: |
          cat assets/env.json
          jq . assets/env.json

      - name: Upload env.json as artifatc
        uses: actions/upload-artifact@v4
        with:
          name: env-file
          path: assets/env.json

  Generate-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        continue-on-error: false
        if: success()

      - name: Generate Enviroment variable
        run: |
          echo "${{ ENV }}" > .env
        shell: bash
        continue-on-error: false
        if: success()
